[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "BAM-torch"
version = "0.1.0.dev0"
description = "uncertainty-aware atomistic simulations at scale"
authors = [
    {name = "Myung Group", email = "myung.group@gmail.com"}
]
license = {text = "LGPL-3.0"}
classifiers = [
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
readme = "README.md"
requires-python = ">=3.11"

# XXX: torch, pyg_lib, torch_*
# should have all been installed beforehand via --find-links <URL>
# (either manually or with install_deps.py)
# instead of having pip automatically install them based on this TOML file.
# Those packages are only listed below as checks.
dependencies = [
    "numpy",
    "scipy",
    "ase",
    "matscipy",
    "torch>=2.5.1",
    "pyg_lib",
    "torch_scatter",
    "torch_sparse",
    "torch_cluster",
    "torch_spline_conv",
    "e3nn",
    "pytorch_warmup",
    "torch_geometric",
    "torch-ema"
]

[project.optional-dependencies]
cueq = ["cuequivariance-torch", "cuequivariance", "cuequivariance-ops-torch-cu12"]
laplace = ["laplace-torch", "torchmetrics"]
group_averaging = ["mendeleev", "pandas"]

[project.urls]
Homepage = "https://github.com/myung-group/BAM-torch"

[tool.setuptools]
packages = {find = {}}

